logging:
  config: 'logback.groovy'
server:
  port: 9200
  error:
    whitelabel:
      enabled: false
  ssl:
      key-store: 'locationsws.jks'
      key-store-password: '123456'
      key-password: '123456'
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password: 12345
    driver-class-name: org.h2.Driver
#  cache:
#    type: none
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/locations_db?useSSL=false&nullNamePatternMatchesAll=true
#    username: root
#    testWhileIdle: true
#    validationQuery: SELECT 1
#  jpa:
#    show-sql: false
#    hibernate:
#      ddl-auto: none
#      naming:
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
#    properties:
#      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#      hibernate.cache.use_second_level_cache: false
#      hibernate.cache.use_query_cache: false
#      hibernate.generate_statistics: false
#      hibernate.hbm2ddl.auto: validate
locations:
  jwtInfo:
    secret: ${jwtSecret:dnsZhcqv0Y3a5zlXgalNHw==}
    expiry: ${jwtExpiry:86400000}
